import React from 'react'
import { createRoot } from 'react-dom/client'
import { Bell, CalendarDays, CheckCircle2, Clock3, FileText, Inbox, LayoutDashboard, Mail, Plus, Search, Settings2, Users, Workflow, X } from 'lucide-react'
import './styles.css'
import type { MailClass } from './domain/models'
import { nextOccurrence } from './services/scheduler'
import { CommandCenter } from './ui/CommandCenter'

const nav = [['Overview', LayoutDashboard], ['Command Center', LayoutDashboard], ['Correspondence', Mail], ['Schedule', CalendarDays], ['Contacts', Users], ['Templates', FileText], ['Automation', Workflow], ['Proof Archive', Inbox]] as const

type Scheduled = { id: string; title: string; recipient: string; meta: string; status: 'Scheduled' | 'Approval required' | 'Draft'; at: string; mailClass: MailClass }
const initialScheduled: Scheduled[] = [
  { id: 'sch_1', title: 'Payment reminder', recipient: 'Acme Supply', meta: 'Standard Mail · 1 page', status: 'Scheduled', at: 'Aug 18 · 9:00 AM', mailClass: 'standard' },
  { id: 'sch_2', title: 'Contract renewal', recipient: 'North Coast HVAC', meta: 'Certified Mail · 3 pages', status: 'Approval required', at: 'Aug 21 · 9:00 AM', mailClass: 'certified' },
  { id: 'sch_3', title: 'Past-due notice', recipient: 'Redwood Office', meta: 'Standard Mail · 2 pages', status: 'Scheduled', at: 'Aug 22 · 9:00 AM', mailClass: 'standard' },
]
const events = [['Aug 14 · 10:42 AM', 'Payment demand mailed', 'Acme Supply · Certified Mail · Tracking added'], ['Aug 14 · 9:18 AM', 'Renewal sequence created', 'North Coast HVAC · 3-step sequence'], ['Aug 13 · 4:05 PM', 'Proof generated', 'Redwood Office · Delivery confirmed']]

function App() {
  const [active, setActive] = React.useState('Overview'); const [scheduled, setScheduled] = React.useState(initialScheduled); const [showComposer, setShowComposer] = React.useState(false); const [search, setSearch] = React.useState('')
  const visible = scheduled.filter(i => `${i.title} ${i.recipient}`.toLowerCase().includes(search.toLowerCase()))
  function createMailing(input: { title: string; recipient: string; date: string; time: string; mailClass: MailClass }) { const date = new Date(`${input.date}T${input.time}:00`); setScheduled(c => [...c, { id: crypto.randomUUID(), title: input.title, recipient: input.recipient, meta: `${input.mailClass[0].toUpperCase()+input.mailClass.slice(1)} Mail · ready to generate`, status: 'Scheduled', at: date.toLocaleString('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}), mailClass: input.mailClass }]); setShowComposer(false) }
  return <div className="app"><aside className="sidebar"><div className="brand"><div className="brand-mark">M</div><div><div className="brand-name">MailMyPDF</div><span className="brand-sub">Business</span></div></div><div className="nav-label">Workspace</div><nav className="nav">{nav.map(([label,Icon])=><button key={label} className={active===label?'active':''} onClick={()=>setActive(label)}><Icon size={16} strokeWidth={1.7}/>{label}</button>)}</nav><div className="sidebar-bottom"><div className="business">North Coast Services</div><div className="business-meta">Business plan · 3 team members</div></div></aside>
    <main className="main"><header className="topbar"><div className="topbar-title">Business correspondence / {active}</div><div className="top-actions"><div className="search"><Search size={15}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search correspondence"/></div><button className="icon-btn"><Bell size={16}/></button><button className="icon-btn"><Settings2 size={16}/></button><div className="avatar">NC</div></div></header><section className="content">
      {active==='Overview'&&<Overview onCreate={()=>setShowComposer(true)} scheduled={visible}/>} {active==='Command Center'&&<CommandCenter onCreateMailing={()=>setShowComposer(true)}/>} {active==='Schedule'&&<SchedulePage scheduled={visible} onCreate={()=>setShowComposer(true)}/>} {active==='Correspondence'&&<Correspondence scheduled={visible}/>} {active==='Contacts'&&<SimplePage eyebrow="Contacts" title="People your business writes to." description="Keep recipients, addresses, references, and correspondence history together."/>} {active==='Templates'&&<SimplePage eyebrow="Templates" title="Your recurring business language." description="Reusable letters become the building blocks for scheduled correspondence."/>} {active==='Automation'&&<Automation/>} {active==='Proof Archive'&&<SimplePage eyebrow="Proof archive" title="A permanent record of what was sent." description="Every completed mailing can retain its document hash, tracking history, delivery facts, and proof bundle."/>}
    </section></main>{showComposer&&<Composer onClose={()=>setShowComposer(false)} onCreate={createMailing}/>}</div>
}
function Overview({onCreate,scheduled}:{onCreate:()=>void;scheduled:Scheduled[]}){return <><div className="header-row"><div><div className="eyebrow">Business correspondence OS</div><h1 className="serif">Everything important,<br/>sent on time.</h1><div className="subtitle">Create, schedule, track, and permanently prove the documents your business sends. MailMyPDF handles the physical mailing so your team can focus on the work.</div></div><button className="primary" onClick={onCreate}><Plus size={15}/>Create mailing</button></div><div className="deadline"><div><div className="label">Next scheduled mailing</div><strong>{scheduled[0]?.title??'Nothing scheduled'} · {scheduled[0]?.recipient??''}</strong></div><div className="deadline-right"><div className="label">{scheduled[0]?.at??'Create your first mailing'}</div><strong>{scheduled.length?'Upcoming':'Ready'}</strong></div></div><div className="stat-grid"><div className="stat"><div className="stat-value">{scheduled.length}</div><div className="stat-label">Scheduled mailings</div></div><div className="stat"><div className="stat-value">8</div><div className="stat-label">Awaiting approval</div></div><div className="stat"><div className="stat-value">37</div><div className="stat-label">In transit</div></div><div className="stat"><div className="stat-value">214</div><div className="stat-label">Delivered</div></div></div><div className="grid"><Queue scheduled={scheduled}/><Calendar/></div><div className="grid lower"><div className="card next"><div className="card-head"><div><div className="card-kicker">Next best action</div><div className="card-title">8 mailings need approval</div></div><Clock3 size={16}/></div><div className="card-body"><div className="item-title">Contract renewal · North Coast HVAC</div><div className="item-meta">Certified Mail · 3 pages · scheduled Aug 21</div><div className="action-row"><button className="primary">Review approvals</button><button className="secondary">Open automation</button></div></div></div><Activity/></div></>}
function Queue({scheduled}:{scheduled:Scheduled[]}){return <div className="card"><div className="card-head"><div><div className="card-kicker">Queue</div><div className="card-title">Upcoming correspondence</div></div><button className="secondary">View schedule</button></div><div className="card-body queue">{scheduled.slice(0,5).map(i=><div className="queue-item" key={i.id}><div><div className="item-title">{i.title} · {i.recipient}</div><div className="item-meta">{i.meta} · {i.at}</div></div><span className={`badge ${i.status==='Approval required'?'red':''}`}>{i.status}</span></div>)}</div></div>}
function Calendar(){return <div className="card"><div className="card-head"><div><div className="card-kicker">This month</div><div className="card-title">Mail calendar</div></div><CalendarDays size={16}/></div><div className="card-body"><div className="calendar">{['M','T','W','T','F','S','S'].map((d,i)=><div className="day-name" key={i}>{d}</div>)}{Array.from({length:35},(_,i)=>{const n=i-3;return <div className={`day ${n<1?'muted':''}`} key={i}><div className="day-num">{n>0?n:''}</div>{[5,8,14,18,21,22,26].includes(n)&&<><div className="dot"/><div className="day-count">{n===18?'4':'1'} mail</div></>}</div>})}</div></div></div>}
function Activity(){return <div className="card"><div className="card-head"><div><div className="card-kicker">Activity</div><div className="card-title">Recent events</div></div><CheckCircle2 size={16}/></div><div className="card-body timeline">{events.map(([date,title,meta])=><div className="event" key={title}><div className="event-date">{date}</div><div className="event-title">{title}</div><div className="event-meta">{meta}</div></div>)}</div></div>}
function SchedulePage({scheduled,onCreate}:{scheduled:Scheduled[];onCreate:()=>void}){return <><PageHeader eyebrow="Schedule" title="Put correspondence on autopilot." description="One-time, recurring, and approval-gated mailings live here." action={onCreate}/><div className="schedule-grid">{scheduled.map(i=><div className="schedule-card" key={i.id}><div className="schedule-date"><span>{i.at.split(' · ')[0]}</span><strong>{i.at.split(' · ')[1]??''}</strong></div><div><div className="item-title">{i.title}</div><div className="item-meta">{i.recipient} · {i.meta}</div></div><span className={`badge ${i.status==='Approval required'?'red':''}`}>{i.status}</span></div>)}</div></>}
function Correspondence({scheduled}:{scheduled:Scheduled[]}){return <><PageHeader eyebrow="Correspondence" title="Every letter in one operational view." description="Draft, scheduled, mailed, delivered, and archived correspondence."/><div className="table-card"><div className="table-head"><span>Document</span><span>Recipient</span><span>Status</span><span>Scheduled</span></div>{scheduled.map(i=><div className="table-row" key={i.id}><strong>{i.title}</strong><span>{i.recipient}</span><span><span className="badge">{i.status}</span></span><span>{i.at}</span></div>)}</div></>}
function Automation(){return <><PageHeader eyebrow="Automation" title="Turn business events into mail." description="Build sequences such as overdue invoice → reminder → demand → certified notice."/><div className="automation-card"><div className="automation-step"><span>WHEN</span><strong>Invoice becomes 14 days overdue</strong></div><div className="automation-arrow">→</div><div className="automation-step"><span>THEN</span><strong>Generate payment reminder</strong></div><div className="automation-arrow">→</div><div className="automation-step"><span>REQUIRE</span><strong>Owner approval</strong></div><div className="automation-arrow">→</div><div className="automation-step"><span>SEND</span><strong>Certified Mail</strong></div></div><button className="primary">Create automation</button></>}
function SimplePage({eyebrow,title,description}:{eyebrow:string;title:string;description:string}){return <><PageHeader eyebrow={eyebrow} title={title} description={description}/><div className="empty-feature"><FileText size={22}/><div><strong>Foundation ready</strong><p>This workspace is connected to the same vendor-neutral document, mailing, tracking, and proof concepts used by MailMyPDF.</p></div></div></>}
function PageHeader({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:()=>void}){return <div className="page-header"><div><div className="eyebrow">{eyebrow}</div><h2 className="serif">{title}</h2><p>{description}</p></div>{action&&<button className="primary" onClick={action}><Plus size={15}/>Create mailing</button>}</div>}
function Composer({onClose,onCreate}:{onClose:()=>void;onCreate:(input:{title:string;recipient:string;date:string;time:string;mailClass:MailClass})=>void}){const[title,setTitle]=React.useState('Payment reminder');const[recipient,setRecipient]=React.useState('');const[date,setDate]=React.useState('2026-08-18');const[time,setTime]=React.useState('09:00');const[mailClass,setMailClass]=React.useState<MailClass>('standard');const[repeat,setRepeat]=React.useState(false);const preview=nextOccurrence({type:repeat?'recurring':'date',at:`${date}T${time}:00`,rrule:repeat?'FREQ=MONTHLY;BYMONTHDAY=1':undefined,timezone:'America/Los_Angeles'},new Date('2026-08-14T12:00:00-07:00'));return <div className="overlay"><div className="composer"><div className="composer-head"><div><div className="eyebrow">New mailing</div><h2 className="serif">Schedule correspondence.</h2></div><button className="icon-btn" onClick={onClose}><X size={17}/></button></div><label>What are you sending?<input value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Recipient<input value={recipient} onChange={e=>setRecipient(e.target.value)} placeholder="Company or contact name"/></label><div className="form-grid"><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Time<input type="time" value={time} onChange={e=>setTime(e.target.value)}/></label></div><label>Mail class<select value={mailClass} onChange={e=>setMailClass(e.target.value as MailClass)}><option value="standard">Standard</option><option value="certified">Certified</option><option value="registered">Registered</option></select></label><label className="check"><input type="checkbox" checked={repeat} onChange={e=>setRepeat(e.target.checked)}/> Repeat monthly</label><div className="composer-preview"><span>Next run</span><strong>{preview?preview.toLocaleString('en-US',{dateStyle:'medium',timeStyle:'short'}):'—'}</strong><small>Drafted now · generated document can be reviewed before send</small></div><div className="composer-actions"><button className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={!recipient.trim()} onClick={()=>onCreate({title,recipient,date,time,mailClass})}>Schedule mailing</button></div></div></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
